### ---- NETWORK PARAMETERS ---- ###

### ETH_1 VIP Network Interface
eth0:
  name: 'eth0'
  ip: '1.1.1.3/24'
  gw: '1.1.1.254'
  mtu: '1500'
  route_to_1: '1.1.1.0/24'
  route_via_1: '1.1.1.254'

# Rsync + carcass
other_node_replication_addr: "{{ srv.carcass.MASTER_ADDR }}"
current_node_replication_addr: "{{ srv.carcass.BACKUP_ADDR }}" 

### ---- KEEPALIVED CONFIG PARAMETERS ---- ###

### All downside params has been tested in production env. Not reconfigure this params if you dont understand what you do.
keepalived:   
  ### - VRRP INSTANCE SECTION - ###
# Defines the default state of ROUTER as MASTER or BACKUP.
  vrrp_state: 'BACKUP'
# Defines the priority of Virtual Router instance. The priority defined for MASTER node shall be higher than all BACKUP nodes. 100 on master, 98 on backup
  vrrp_priority: '98'

  ### - UNICAST ADDRESSES SECTION - ###
# Unicast addr of the current node. Need for sw-over MASTER node, when MASTER node is shutting down.
  current_node_unicast_ip_addr: "{{ srv.carcass.BACKUP_ADDR }}"
# Unicast addr of the secondary node. Need for sw-over MASTER node, when MASTER node is shutting down.
  secondary_node_unicast_ip_addr: "{{ srv.carcass.MASTER_ADDR }}"